export const SIGN_IN_FAIL = 'SIGN_IN_FAIL'
export const SIGN_IN_START = 'SIGN_IN_START'
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'

export const SIGN_UP_FAIL = 'SIGN_UP_FAIL'
export const SIGN_UP_START = 'SIGN_UP_START'
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS'

export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH"

export const SUBMIT_POST_FAIL = 'SUBMIT_POST_FAIL'
export const SUBMIT_POST_START = "SUBMIT_POST_START"
export const SUBMIT_POST_SUCCESS = 'SUBMIT_POST_SUCCESS'

export const FETCH_POSTS_FAIL = 'FETCH_POSTS_FAIL'
export const FETCH_POSTS_START = 'FETCH_POSTS_START'
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'

export const FETCH_FULLPOST_FAIL = 'FETCH_FULLPOST_FAIL'
export const FETCH_FULLPOST_START = 'FETCH_FULLPOST_START'
export const FETCH_FULLPOST_SUCCESS = 'FETCH_FULLPOST_SUCCESS'

export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL'
export const FETCH_USERS_START = 'FETCH_USERS_START'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'

export const EDIT_POST_FAIL = 'EDIT_POST_FAIL'
export const EDIT_POST_START = 'EDIT_POST_START'
export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS'

