export const SIGN_IN_CRED = 'SIGN_IN_CRED'
export const SIGN_UP_CRED = 'SIGN_UP_CRED'

export const SUBMIT_POST_FAIL = 'SUBMIT_POST_FAIL'
export const SUBMIT_POST_START = "SUBMIT_POST_START"
export const SUBMIT_POST_SUCCESS = 'SUBMIT_POST_SUCCESS'

export const FETCH_POSTS_FAIL = 'FETCH_POSTS_FAIL'
export const FETCH_POSTS_START = 'FETCH_POSTS_START'
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'

export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL'
export const FETCH_USERS_START = 'FETCH_USERS_START'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'


